AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
