sudo: false
branches:
  except:
  - gh-pages
cache: bundler
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem update --system 2.4.5
  - gem --version
  - gem install inspec rake rubocop --no-rdoc --no-ri
script:
  - 'rake lint:ruby'
  - 'rake inspec:check'
